service: serverless-daynmodb

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true
  basePath: learn/
  stage: ${opt:stage, self:provider.stage}
  namespace: ${self:service}-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  cfLogs: true
  profile: learnServerless
  stackTags:
  AppName: ${self:service}
  Namespace: ${self:custom.namespace}
  Author: Mais Eid 

# you can add statements to the Lambda function's IAM Role here
iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  hello:
    handler: handler.hello

  createQuote:
    handler: create.main
    events:
      - http:
          path: ${self:custom.basePath}create
          method: post
          cors: true
          request:
            parameters:
              paths:
                quoteId: true
  queryGetQuote:
    handler: get.queryGet
    events:
      - http:
          path: ${self:custom.basePath}get/query/{quoteId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                quoteId: true        
  scanGetQuote:
    handler: get.scanGet
    events:
      - http:
          path: ${self:custom.basePath}get/scan/{quoteId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                quoteId: true
  updateQuote:
    handler: update.main
    events:
      - http:
          path: ${self:custom.basePath}update/{quoteId}
          method: put
          cors: true
          request:
            parameters:
              paths:
                quoteId: true
  deleteQuote:
    handler: delete.main
    events:
      - http:
          path: ${self:custom.basePath}delete/{quoteId}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                quoteId: true