service: serverless-cloudsearch

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: ServerlessTraining
  stackTags:
    AppName: serverless_cloudsearch
    Author: Mais Eid 

functions:
  helloCloudSearch:
    handler: handler.helloCloudSearch
    memorySize: 128
    timeout: 3
    tags:
      Func: helloCloudSearch
    events:
      - http:
          path: serverless/cloudsearch/{p_name}
          method: get
          cors: true
          request:
            parameters:
              paths:
                p_name: true