service: serverless-RDS

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true
  basePath: learn/
  stage: ${opt:stage, self:provider.stage}
  namespace: ${self:service}-${self:custom.stage}
  lambdaExecSecurityGroup:  sg-1b78126e
  SUBNET_ID_A: subnet-ae0cad81
  SUBNET_ID_B: subnet-69372665
  SUBNET_ID_C: subnet-a177adfc


provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  cfLogs: true
  profile: learnServerless
  stackTags:
  AppName: ${self:service}
  Namespace: ${self:custom.namespace}
  Author: Mais Eid 


functions:
  helloRDS:
    handler: handler.main
    vpc:
       securityGroupIds:
        - ${self:custom.lambdaExecSecurityGroup}
       subnetIds:
        - ${self:custom.SUBNET_ID_A}
        - ${self:custom.SUBNET_ID_B}
        - ${self:custom.SUBNET_ID_C}
    events:
      - http:
          path: ${self:custom.basePath}rds
          method: get
          cors: true